#!/usr/bin/env python3
"""Build KNOWLAGE1.3.zip and regenerate its manifests.

Packs the knowledge documents, the project source snapshot, the git-history snapshot,
and the retained memory snapshots into a single archive, then writes MANIFEST.md and
PACK_MANIFEST.json from what was actually packed.

Usage:
    python tools/build_knowlage_archive.py [--repo PATH] [--out PATH] [--skip-source]

The pack directory is inferred from this file's location, so the script can be run from
anywhere.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import zipfile
from datetime import date
from pathlib import Path

PACK_ROOT = Path(__file__).resolve().parent.parent
PACK_NAME = PACK_ROOT.name
VERSION = "1.3"

# Directories never copied into the source snapshot: build output, dependency trees,
# caches, and the two folders that hold live audit evidence and run output.
EXCLUDED_DIRS = {
    ".git",
    ".venv",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "htmlcov",
    "inbox",
    "outputs",
    "knowledge",
}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".coverage"}
EXCLUDED_PREFIXES = (".pytest-tmp", ".pytest_tmp", ".pytest-stage", "pytest-cache-files-")

# Knowledge documents, in the order they appear in MANIFEST.md.
KNOWLEDGE_DOCS = [
    "README.md",
    "SESSION_SUMMARY.md",
    "ERROR_LEDGER.md",
    "HARD_LESSONS.md",
    "DURABLE_FIXES.md",
    "FAILED_ASSUMPTIONS.md",
    "DO_NOT_REPEAT.md",
    "ENGAGEMENT_LESSONS_SUGGESTION.md",
    "AAR_AUDIT_REPORT_PLAYBOOK.md",
    "FIELD_AUTHORITY_AND_COMPLETENESS.md",
    "VALIDATION_AND_REGRESSION.md",
    "KNOWLEDGE_SOURCES_INDEX.md",
    "GOOGLE_DRIVE_UPDATE_SUGGESTIONS.md",
    "CHANGELOG_FROM_KNOWLAGE_1_2.md",
    "FUTURE_AGENT_NOTES.md",
]


def is_excluded(path: Path) -> bool:
    for part in path.parts:
        if part in EXCLUDED_DIRS or part.startswith(EXCLUDED_PREFIXES):
            return True
    return path.suffix in EXCLUDED_SUFFIXES


def sha256_of(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def snapshot_source(repo: Path, dest: Path) -> int:
    """Copy the project source tree, minus build state and evidence folders."""
    if dest.exists():
        shutil.rmtree(dest)
    count = 0
    for src in sorted(repo.rglob("*")):
        rel = src.relative_to(repo)
        if is_excluded(rel) or not src.is_file():
            continue
        target = dest / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, target)
        count += 1
    return count


def snapshot_git_history(repo: Path, dest: Path) -> None:
    """Record commit history and branch state as text."""
    dest.mkdir(parents=True, exist_ok=True)
    commands = {
        "commit-log.txt": ["git", "log", "--pretty=format:%h %ad %an%n    %s", "--date=short"],
        "branches.txt": ["git", "branch", "-a", "-v"],
        "head.txt": ["git", "rev-parse", "HEAD"],
        "file-count.txt": ["git", "ls-files"],
    }
    for filename, command in commands.items():
        try:
            output = subprocess.run(
                command, cwd=repo, capture_output=True, text=True, check=True
            ).stdout
        except (subprocess.CalledProcessError, FileNotFoundError) as exc:
            output = f"(unavailable: {exc})\n"
        (dest / filename).write_text(output, encoding="utf-8")


def packed_files(root: Path) -> list[Path]:
    """Every file to be packed, manifests excluded (they describe the rest)."""
    manifests = {root / "MANIFEST.md", root / "PACK_MANIFEST.json"}
    return sorted(
        path
        for path in root.rglob("*")
        if path.is_file() and path not in manifests and not is_excluded(path.relative_to(root))
    )


def write_manifests(root: Path, files: list[Path]) -> None:
    records = [
        {
            "file": str(path.relative_to(root)).replace("\\", "/"),
            "bytes": path.stat().st_size,
            "sha256": sha256_of(path),
        }
        for path in files
    ]
    by_name = {record["file"]: record for record in records}

    total_bytes = sum(record["bytes"] for record in records)
    lines = [
        f"# Manifest — {PACK_NAME}",
        "",
        "Generated by `tools/build_knowlage_archive.py`. Do not hand-edit.",
        "",
        f"Version: {VERSION} · Built: {date.today().isoformat()} · "
        f"Files: {len(records)} · Bytes: {total_bytes:,}",
        "",
        "## Knowledge documents",
        "",
        "| File | Bytes | SHA-256 |",
        "|---|---:|---|",
    ]
    for name in KNOWLEDGE_DOCS:
        record = by_name.get(name)
        if record:
            lines.append(f"| `{name}` | {record['bytes']} | `{record['sha256']}` |")

    listed = set(KNOWLEDGE_DOCS)
    others = [r for r in records if r["file"] not in listed]
    top_level = [r for r in others if "/" not in r["file"]]
    memory = [r for r in others if r["file"].startswith("memory/")]
    tools = [r for r in others if r["file"].startswith("tools/")]
    source = [r for r in others if r["file"].startswith("source/")]

    for title, group in (
        ("Other top-level files", top_level),
        ("Retained memory", memory),
        ("Build tooling", tools),
    ):
        if not group:
            continue
        lines += ["", f"## {title}", "", "| File | Bytes | SHA-256 |", "|---|---:|---|"]
        lines += [f"| `{r['file']}` | {r['bytes']} | `{r['sha256']}` |" for r in group]

    if source:
        source_bytes = sum(r["bytes"] for r in source)
        lines += [
            "",
            "## Source snapshot",
            "",
            f"`source/` holds {len(source)} files, {source_bytes:,} bytes. "
            "Per-file hashes are in `PACK_MANIFEST.json`.",
        ]

    lines.append("")
    (root / "MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")

    (root / "PACK_MANIFEST.json").write_text(
        json.dumps(
            {
                "package": PACK_NAME,
                "version": VERSION,
                "built": date.today().isoformat(),
                "purpose": "repeatable AAR B-2 / QAPE audit method knowledge, with project source and memory snapshots",
                "file_count": len(records),
                "total_bytes": total_bytes,
                "files": records,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )


def build_zip(root: Path, out_path: Path) -> None:
    files = packed_files(root) + [root / "MANIFEST.md", root / "PACK_MANIFEST.json"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for path in sorted(set(files)):
            archive.write(path, f"{PACK_NAME}/{path.relative_to(root)}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=PACK_ROOT.parent.parent,
                        help="Project repository root to snapshot")
    parser.add_argument("--out", type=Path, default=PACK_ROOT.parent / f"KNOWLAGE{VERSION}.zip",
                        help="Archive path to write")
    parser.add_argument("--skip-source", action="store_true",
                        help="Reuse the existing source snapshot instead of re-copying")
    args = parser.parse_args()

    if not args.skip_source:
        copied = snapshot_source(args.repo, PACK_ROOT / "source" / "repo")
        snapshot_git_history(args.repo, PACK_ROOT / "source" / "git-history")
        print(f"source snapshot: {copied} files from {args.repo}")

    files = packed_files(PACK_ROOT)
    write_manifests(PACK_ROOT, files)
    build_zip(PACK_ROOT, args.out)
    print(f"manifests: {len(files)} files hashed")
    print(f"archive:   {args.out} ({args.out.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
