from __future__ import annotations

from shared_core.template_registry import template_map

# Registry-backed filenames (48 M-1002 blanks); see config/m1002_template_registry.json
FORM_TEMPLATES = template_map()

FIELD_ALIASES = {
    "owner_name": [
        "tank car or service equipment owner (tco/seo) name",
        "tank car or service equipment owner (tco/seo)",
        "tank car or service equipment owner (tco/seo) name",
        "tank car or service equipment owner (tco/seo) name",
        "tank car or lining/coating owner (tco / l/co) name",
        "tank car coating owner (tco / l/co) name",
        "tank car or coating owner (tco / l/co) name",
        "tank car or service equipment owner (tco/seo) name",
        "tank car or service equipment owner (tco/seo) name",
        "customer",
    ],
    "permission_date": ["date permission received"],
    "written_instructions": ["written instructions from tco", "written instructions from tco/seo", "written instructions from tco / l/co"],
    "car_mark": ["car mark and number", "car reporting mark and number", "car initial and number"],
    "tank_spec": ["tank car design specification", "tank car design spec", "tank specification", "tank car design spec/stencil spec"],
    "stencil_spec": ["stencil specification", "tank car stencil spec", "stenciled specification"],
    "service_equipment_description": ["service equipment description", "description of service equipment", "description of device being removed", "description of device being replaced"],
    "aar_form_no": ["aar form and (aar no.)", "aar form 4-2 (aar no.)", "aar form number", "reference aar form 4-2 (aar no.)", "aar no."],
    "drawing_number": ["drawing number", "applicable arrangement drawing #", "4-2 drawing number"],
    "drawing_revision": ["revision", "rev", "drawing revision"],
    "drawing_type": ["4-2 drawing type", "drawing"],
    "fittings_arrangement": ["fittings arrangement", "bottom fittings arrangement (bov)", "precedent applicable arrangement drawing"],
    "applicant": ["applicant"],
    "manufacturer": ["manufacturer", "manufacturer’s model number", "manufacturer’s design or type number", "manufacturer name", "pressure relief device (prd) c. manufacturer"],
    "model_number": ["model number", "manufacturer’s model number", "model/type number", "base model number (d104)", "description of service equipment"],
    "serial_number": ["serial number", "unique serial number", "valve serial no", "d serial number", "identification number", "aar component identification (cid)"],
    "material_spec": ["material specification", "lining/coating material", "coating material", "coating type", "material"],
    "material_id": ["id", "tracing no.", "aar approval number", "aar component identification (cid)"],
    "status_indicator": ["status ind.", "status indicator"],
    "personnel_id": ["personnel id", "qualified personnel id", "qualified coatings inspector id", "qualified coatings applicator id", "facility representative (print name)", "inspector (print name)"],
    "function_performed": ["function performed"],
    "training_date": ["date received function specific training"],
    "pitp_doc_name": ["pitp document name"],
    "pitp_id": ["pitp id"],
    "approved_by": ["approved by", "ndt level iii approver", "management representative (print name)"],
    "date_approved": ["date approved", "date completed", "qualification date (as tested) (d113)"],
    "result": ["result (including accepted or rejected)", "results (accepted or rejected) including applicable tolerance"],
    "procedure_id": ["procedure id", "tcid procedure"],
    "record_form_id": ["record/form id"],
    "equipment_type": ["equipment type", "measure and test equipment", "welding machine", "wire feeder", "thermometer", "test bench"],
    "equipment_id": ["id", "pressure gauge id", "temperature gage id", "temperature gauge id", "utt transducer serial #"],
    "calibration_date": ["calibration date"],
    "calibration_due": ["calibration due"],
    "location": ["location in facility where maintenance process was observed", "location in facility where final inspection & qualification event was observed", "location in facility where final inspection and leakage test was observed", "location in facility where marking of valve was observed", "location in facility where marking of instrument was observed", "location in facility stenciling was observed", "location in facility where final inspection/qualification event was observed", "location in facility where final inspection and qualification event was observed", "location in facility where installation of new interior coating was observed", "location in facility where removal of lining/coating was observed", "location in facility ndt methods were performed"],
    "ndt_technician_id": ["ndt technician id"],
    "ndt_level": ["level qualified (i, ii, iii)", "level qualified"],
    "ndt_method": ["ndt method(s)", "ndt method", "leak testing (lt) type"],
    "date_qualified": ["date qualified"],
    "qualification_expiration_date": ["qualification expiration date"],
    "visual_acuity_date": ["date of visual acuity exam", "visual acuity date"],
    "visual_acuity_due": ["due date visual acuity exam", "visual acuity expiration date"],
    "hold_soak_time": ["lt procedure hold / soak time", "observed hold / soak time"],
    "dwell_time": ["lt procedure dwell time", "observed dwell time"],
    "gas_or_medium": ["lt procedure gas, liquid, or medium type and concentration", "observed gas, liquid, or medium type and concentration", "actual gas, liquid, or medium type and concentration", "gas or medium", "medium/liquid used (leak/fluid)"],
    "gauge_pressure": ["lt procedure gauge pressure (psi)", "observed gauge pressure (psi)", "actual gauge pressure (psi)", "pressure rating (psig)", "set pressure", "flow rating pressure (psig)"],
    "temperature_range": ["temperature range", "pressure and/or temperature limitations"],
    "leak_detector_manufacturer": ["leak detector manufacturer"],
    "leak_detector_type": ["leak detector type"],
    "facility_temperature": ["temperature in facility in where lt was observed", "temperature at time of application of stencil", "temperature at time of application of qualification stencil", "ambient temperature", "surface temperature", "dew point", "relative humidity"],
    "marking_location": ["location of marking on valve", "location of marking on instrument", "location of marking on safety relief device"],
    "traceability": ["traceability (i.e., station stencil)", "means for traceability", "where are markings required accomplished"],
    "station_stencil": ["station stencil", "observed marked station stencil", "observed station stencil entry", "station stencil of the c4a or c4m certified facility (effective 7/1/2021)"],
    "qualification_stencil": ["qualified", "due", "service equipment", "lining", "prd:"],
    "pressure_rating": ["pressure rating (psig)", "set pressure (psig)", "start-to-discharge pressure, psi", "vapor-tight-pressure", "vapor tight pressure"],
    "specific_gravity": ["specific gravity (gauging devices only)"],
    "official_flow_capacity": ["official flow capacity (cubic feet per minute of air at standard conditions)"],
    "flow_rating_pressure": ["flow rating pressure (psig)"],
    "cid": ["aar component identification (cid)"],
    "certifier_id": ["certifier id (d118)"],
    "description_of_work": ["description of work performed"],
    "patch_plate_size": ["patch plate size"],
    "observed_fillet_weld_size": ["observed fillet weld size"],
    "observed_weld_length": ["observed weld length"],
    "protective_coating_type_date": ["protective coating type/date", "protective coating type"],
}

DIRECT_VALUE_FIELDS = {
    "owner_name", "permission_date", "written_instructions", "car_mark", "tank_spec", "stencil_spec",
    "service_equipment_description", "aar_form_no", "drawing_number", "drawing_revision", "drawing_type",
    "fittings_arrangement", "applicant", "manufacturer", "model_number", "serial_number", "material_spec",
    "material_id", "status_indicator", "personnel_id", "function_performed", "training_date", "pitp_doc_name",
    "pitp_id", "approved_by", "date_approved", "result", "procedure_id", "record_form_id", "equipment_type",
    "equipment_id", "calibration_date", "calibration_due", "location", "ndt_technician_id", "ndt_level",
    "ndt_method", "date_qualified", "qualification_expiration_date", "visual_acuity_date", "visual_acuity_due",
    "hold_soak_time", "dwell_time", "gas_or_medium", "gauge_pressure", "temperature_range",
    "leak_detector_manufacturer", "leak_detector_type", "facility_temperature", "marking_location", "traceability",
    "station_stencil", "pressure_rating", "specific_gravity", "official_flow_capacity", "flow_rating_pressure",
    "cid", "certifier_id", "description_of_work",
    "patch_plate_size", "observed_fillet_weld_size", "observed_weld_length", "protective_coating_type_date",
}
